# Generated by Django 2.2.14 on 2022-11-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='marked_price',
        ),
    ]
